AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'features/support/env.rb'
    - 'script/cucumber'
    - 'Gemfile'

Metrics/LineLength:
  Max: 150
  Exclude:
    - 'features/**/*'
    - 'Gemfile'

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false